export const courseResult = [
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0133", 
        course_name: "資料庫管理系統", 
        course_teacher: "連中岳",
        num: "3", 
        list: "專業必修",
        classroom: "B210",
        day: "5",
        time: "2~4"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0035", 
        course_name: "組織行為學", 
        course_teacher: "杜清敏",
        num: "3", 
        list: "專業選修",
        classroom: "F402",
        day: "4",
        time: "6~8"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0036", 
        course_name: "健康經濟學", 
        course_teacher: "陳亮均",
        num: "2", 
        list: "專業選修",
        classroom: "G201",
        day: "3",
        time: "6~7"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0131", 
        course_name: "網路程式設計", 
        course_teacher: "蔡坤孝",
        num: "3", 
        list: "專業選修",
        classroom: "F602",
        day: "1",
        time: "5~7"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "1459", 
        course_name: "商業智慧", 
        course_teacher: "杜清敏",
        num: "3", 
        list: "專業選修",
        classroom: "F602",
        day: "2",
        time: "2~4"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "1568", 
        course_name: "健康照護物聯網導論", 
        course_teacher: "洪論評",
        num: "3", 
        list: "專業選修",
        classroom: "F602",
        day: "1",
        time: "2~4"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "1765", 
        course_name: "機器學習程式設計", 
        course_teacher: "陳彥宏",
        num: "3", 
        list: "專業選修",
        classroom: "F602",
        day: "3",
        time: "2~4"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0080", 
        course_name: "作業系統", 
        course_teacher: "吳承翰",
        num: "3", 
        list: "專業必修",
        classroom: "B210",
        day: "2",
        time: "8~10"
    },
  ];
  