export const courseResult = [
    { 
        semester: "1122",
        program: "學士後多元專長",
        department: "資訊管理系",
        grade: "2",
        course_id: "0133", 
        course_name: "產業經營績效之大數據分析", 
        course_teacher: "連中岳",
        num: "3", 
        list: "專業必修",
        classroom_key: "B",
        classroom: "210",
        day: "星期5",
        time: "2,3,4"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0035", 
        course_name: "組織行為學", 
        course_teacher: "杜清敏",
        num: "3", 
        list: "專業選修",
        classroom_key: "F",
        classroom: "402",
        day: "星期4",
        time: "6,7,8"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0036", 
        course_name: "健康經濟學", 
        course_teacher: "陳亮均",
        num: "2", 
        list: "專業選修",
        classroom_key: "G",
        classroom: "201",
        day: "星期3",
        time: "6,7"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0131", 
        course_name: "網路程式設計", 
        course_teacher: "蔡坤孝",
        num: "3", 
        list: "專業選修",
        classroom_key: "F",
        classroom: "602",
        day: "星期1",
        time: "5,6,7"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "1459", 
        course_name: "商業智慧", 
        course_teacher: "杜清敏",
        num: "3", 
        list: "專業選修",
        classroom_key: "F",
        classroom: "602",
        day: "星期2",
        time: "2,3,4"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "1568", 
        course_name: "健康照護物聯網導論", 
        course_teacher: "洪論評",
        num: "3", 
        list: "專業選修",
        classroom_key: "F",
        classroom: "602",
        day: "星期1",
        time: "2,3,4"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "1765", 
        course_name: "機器學習程式設計", 
        course_teacher: "陳彥宏",
        num: "3", 
        list: "專業選修",
        classroom_key: "F",
        classroom: "602",
        day: "星期3",
        time: "2,3,4"
    },
    { 
        semester: "1122",
        program: "四技",
        department: "資訊管理系",
        grade: "2",
        course_id: "0080", 
        course_name: "作業系統", 
        course_teacher: "吳承翰",
        num: "3", 
        list: "專業必修",
        classroom_key: "B",
        classroom: "210",
        day: "星期2",
        time: "8,9,10"
    },
  ];
  